### ISSUE TITLE
Could not fetch version for kano-apps

### ISSUE THREAD

**Issue by FMDSF** [mandre/kano-i18n-sync#2]
Hi Martin,

I retested and still have the same issue. Couldn't fetch version for kano-apps.
Can you help me out? What information do you need else?

That's what happened on my system:
```
[fmdsf@localhost kano-i18n-sync]$ ./pull_translations.py --lang de

Copying sudoers files



Syncing translations for kano-apps

Fetching package version for kano-apps

Could not fetch version for kano-apps

```

**Comment by mandre** [comment]
Hi! I finally took the time to re-install Kano from scratch and was able to replicate your issue. This was caused by `kano-apps-i18n-orig` package not being installed on the system. I've i[mproved the logging](https://github.com/mandre/kano-i18n-sync/commit/72652e239cbd9d4914f3d06dd084c3c76d7e367c) that should now print the exact reason why it failed to fetch package version, and also added more documentation about [all the steps needed to prepare kano](https://github.com/mandre/kano-i18n-sync/commit/a85ccedb85f90c3c1c4e2fae9e04d6ace45afb2b). Let me know if this works for you.

**Comment by FMDSF** [comment]
Hello! :)
I went through the steps. Without any error message until the end...

scp sudoers.conf kano: -> **OK**
sudo chown root.root sudoers.conf -> **OK**
sudo mv sudoers.conf /etc/sudoers.d/kano-i18n-sync_conf -> **OK**
sudo apt-get update-> **OK**
sudo apt-get install *-i18n-orig zip -> **OK**
sudo dpkg-reconfigure locales -> Was already on locales DE -> **OK**

./pull_translations.py --lang de -> **Error see below:**

    fmdsf@localhost kano-i18n-sync]$ ./pull_translations.py --lang de

    Traceback (most recent call last):

    File "./pull_translations.py", line 160, in <module>

    ssh.connect(**cfg)

    File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect

    passphrase,

    File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 764, in _auth

    raise saved_exception

    File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 740, in _auth

    self._transport.auth_publickey(username, key)

    File "/usr/local/lib/python3.7/site-packages/paramiko/transport.py", line 1580, in auth_publickey

    return self.auth_handler.wait_for_response(my_event)

    File "/usr/local/lib/python3.7/site-packages/paramiko/auth_handler.py", line 250, in      
    wait_for_response

    raise e

    paramiko.ssh_exception.AuthenticationException: Authentication failed.

    [fmdsf@localhost kano-i18n-sync]$

**Comment by mandre** [comment]
The error says `Authentication failed`. Double check you can connect to your Kano device simply with the `ssh kano` command.

https://github.com/mandre/kano-i18n-sync#enable-ssh-access-to-kano

**Comment by FMDSF** [comment]
I have no problem in connecting to my kano device via `ssh kano`.
The steps described in your section **Enable SSH access to Kano** have been done and worked so far.
